// Angular/WebGUI/src/app/components/pick/pick.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-pick',
  templateUrl: './pick.component.html'
})
export class PickComponent {
  // TODO: change to new data.json
  @Input() spreadList;

  pickVisitor(item: any) {
    console.log("visitor pick " + item);
  }

  pickHome(item: any) {
    console.log("home pick " + item);
  }

}

<div class="container">
  <h2>User Pick Table</h2>
  <table class="table table-dark table-hover">
    <thead>
      <tr>
        <th>Time</th>
        <th>Matchup</th>
        <th>Side</th>
        <th>O/U</th>
      </tr>
    </thead>
    <tbody>
      <tr *ngFor="let item of spreadList; let id=index">
        <td>{{item.gameDateTime | date:'EEEE M/d/yy h:mm a'}}</td>
        <td>
          <p>{{item.visitor}}</p>
          <p>{{item.home}}</p>

        </td>
        <td>
          <button type="submit" class="btn btn-primary d-block"
          (click)="pickVisitor(item)">{{item.visitorLine}}</button>
          <button type="submit" class="btn btn-primary d-block"
          (click)="pickHome(item)">{{item.homeLine}}</button>
        </td>
        <td>
          <button type="submit" class="btn btn-primary d-block">O {{item.OULine}}</button>
          <button type="submit" class="btn btn-primary d-block">U {{item.OULine}}</button>
        </td>
      </tr>
    </tbody>
  </table> <!-- pick -->

  <h2>Bet Card Table</h2>
  <table class="table table-dark table-hover; let id=index">
    <thead>
      <tr>
        <th>Selection</th>
        <th>Line</th>
        <th>Amount</th>
        <th>(cancel)</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>SEA</td>
        <td>-2.0</td>
        <td>
          <input type="text" name="betAmt" value="100">
        </td>
        <td>
          <button type="submit" class="btn btn-primary d-block">Delete</button>
        </td>
      </tr>
      <tr>
        <td>Over TB/NO</td>
        <td>47.5</td>
        <td>
          <input type="text" name="betAmt" value="200">
        </td>
        <td>
          <button type="submit" class="btn btn-primary d-block">Delete</button>
        </td>
      </tr>

    </tbody>
  </table>
  <div>
    <button type="submit" class="btn btn-primary d-block">Send</button>
    <button type="submit" class="btn btn-primary d-block">Clear</button>
  </div>

// React/web-gui/src/components/Pick.js
import React, { Component } from 'react';
import Moment from 'react-moment';

class Pick extends Component {

    render() {
        return (
            <div>
                <div className="container">
                    <h2>User Pick Table</h2>
                    <table className="table table-dark table-hover">
                        <thead>
                            <tr>
                                <th>Time</th>
                                <th>Matchup</th>
                                <th>Side</th>
                                <th>O/U</th>
                            </tr>
                        </thead>
                        <tbody>
                            {this.props.spreads.map(item => (
                                <tr >
                                    <td> {item.gameId} <Moment date={item.gameDateTime}
                                        parse="YYYY-MM-dd hh:mm"
                                        format="dddd, YYYY/MM/DD h:mma"></Moment>
                                    </td>
                                    <td>
                                        <p>{ item.visitor }</p>
                                        <p>{ item.home }</p>

                                    </td>
                                    <td>
                                        <button type="submit" className="btn btn-primary d-block">{ item.visitorLine }</button>
                                        <button type="submit" className="btn btn-primary d-block">{ item.homeLine }</button>
                                    </td>
                                    <td>
                                        <button type="submit" class="btn btn-primary d-block">O { item.OULine }</button>
                                        <button type="submit" class="btn btn-primary d-block">U { item.OULine }</button>
                                    </td>
                                </tr>
                            ))}
                        </tbody>
                    </table>

                    <h2>Bet Card Table</h2>
                    <table className="table table-dark table-hover; let id=index">
                        <thead>
                            <tr>
                                <th>Selection</th>
                                <th>Line</th>
                                <th>Amount</th>
                                <th>(cancel)</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>SEA</td>
                                <td>-2.0</td>
                                <td>
                                    <input type="text" name="betAmt" value="100" />
                                </td>
                                <td>
                                    <button type="submit" className="btn btn-primary d-block">Delete</button>
                                </td>
                            </tr>
                            <tr>
                                <td>Over TB/NO</td>
                                <td>47.5</td>
                                <td>
                                    <input type="text" name="betAmt" value="200" />
                                </td>
                                <td>
                                    <button type="submit" className="btn btn-primary d-block">Delete</button>
                                </td>
                            </tr>

                        </tbody>
                    </table>
                    <div>
                        <button type="submit" className="btn btn-primary d-block">Send</button>
                        <button type="submit" className="btn btn-primary d-block">Clear</button>
                    </div>
                </div>
            </div>
        )
    }
}
export default Pick;
