// Angular/WebGUI/src/app/components/spread/spread.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-spread',
  templateUrl: './spread.component.html'
})
export class SpreadComponent {
  @Input() spreadList;

}

<div class="container">
    <h2>Weekly Spread Table</h2>
    <table class="table table-dark table-hover">
        <thead>
            <tr>
                <th>Time</th>
                <th>Matchup</th>
                <th>Side</th>
                <th>O/U</th>
            </tr>
        </thead>
        <tbody>
            <tr *ngFor="let item of spreadList">
                <td>{{item.gameDateTime | date:'EEEE M/d/yy h:mm a'}}</td>
                <td>
                    <p>{{item.visitor}}</p>
                    <p>{{item.home}}</p>

                </td>
                <td>
                    <p>filler</p>
                    <p><input type="text" name="gameSpread" value={{item.lineSide}}></p>
                </td>
                <td>
                    <p>filler</p>
                    <p><input type="text" name="ouSpread" value={{item.lineOU}}></p>
                </td>
            </tr>
        </tbody>
    </table>
</div>
<div>
    <button type="submit" class="btn btn-primary">Save</button>
</div>

// React/web-gui/src/components/Spread.js
import React, { Component } from 'react';
import { FaTimes } from 'react-icons/fa';
import Moment from 'react-moment';

class Spread extends Component {
    /*
    render() {
        const listItems = this.props.spreads.map(item => (
            <div>
                <div>{item.gameDateTime}</div>
                <div>{item.visitor}</div>
                <div>{item.home}</div>
            </div>
        ));
        return <div>{listItems}</div>;
    } */
    render() {
        return (
            <div className="weekly-spread">
                <h2>Weekly Spread Table</h2>
                <table class="table table-dark table-hover">
                    <thead>
                        <tr>
                            <th>Time</th>
                            <th>Matchup</th>
                            <th>Line</th>
                            <th>O/U</th>
                        </tr>
                    </thead>
                    <tbody>
                        {this.props.spreads.map(item => (
                        <tr>
                            <td> {item.gameDateTime} </td>
                            <td>
                                <p>{item.visitor}</p>
                                <p>{item.home}</p>
                            </td>
                            <td>
                                <p>{item.visitorLine}</p>
                                <span contenteditable="true" >{item.homeLine}</span>
                            </td>
                            <td>
                                <p>---</p>
                                <span contenteditable="true" >{item.OULine}</span>
                            </td>
                        </tr>
                        ))}
                    </tbody>
                </table>
                <div class="form-group">
                    <button type="submit" class="btn btn-primary">Save</button>
                </div>
            </div >
        );
    } // render
}

export default Spread;
